[[redirects]]
  from = "/api/traxo/*"
  to = "/.netlify/functions/traxo-proxy"
  status = 200
  force = true
  

[[redirects]]
  from = "/api/jeep/*"
  to = "/.netlify/functions/jeep-proxy"
  status = 200
  force = true
