// JEEP - Connected Vehicle India Plaform - Alert message
// Protocol definition files using Protocol Buffers - Google's data interchange format

syntax = "proto3";
package stla.cvip.jeep;
option java_package = "stla.cvip.jeep";
option java_outer_classname = "StlaJeepAlert";

import "jeep_alert.proto";
import "jeep_common.proto";
import "timestamp.proto";

message AlertMessage {
	string message_id = 1;
	eTboxOperatingState tbox_operating_state = 2;
	eTboxApplicationState e_tbox_application_state = 3;
    	eTboxeSimState tbox_esim_state = 4;
	string version = 5;
	google.protobuf.Timestamp time_stamp = 6;
	AlertPayload alertPayload = 7;
}
