/**
 * CAN Code Generator Utility
 * Generates MISRA-C:2012 compliant C code for embedded CAN signal decoding.
 */

// -----------------------------------------------------------------------------
// 1. Header Generation (can_config.h)
// -----------------------------------------------------------------------------
export const generateCanConfigH = () => {
    return `/**
 * @file can_config.h
 * @brief CAN Signal Configuration Header
 *
 * Generated by Rule Engine Dashboard
 * Standard: MISRA-C:2012
 */

#ifndef CAN_CONFIG_H
#define CAN_CONFIG_H

#include <stdint.h>
#include <stdbool.h>

/**
 * @brief Endianness enumeration
 */
typedef enum
{
    ENDIAN_LITTLE = 0,
    ENDIAN_BIG
} endian_t;

/**
 * @brief CAN Signal Configuration Structure
 * 
 * Defines the static configuration for a single CAN signal.
 * All fields are fixed-width types for deterministic behavior.
 */
typedef struct
{
    uint32_t can_id;    /**< CAN Message ID (Standard/Extended) */
    uint8_t  start_bit; /**< Start bit position (0-63) */
    uint8_t  length;    /**< Length in bits (1-64) */
    endian_t endian;    /**< Byte order */
    float    factor;    /**< Scaling factor */
    float    offset;    /**< Scaling offset */
    float    min;       /**< Minimum valid physical value */
    float    max;       /**< Maximum valid physical value */
} can_signal_t;

/**
 * @brief Global Signal Table
 */
extern const can_signal_t can_signals[];

/**
 * @brief Total number of configured signals
 */
extern const uint16_t CAN_SIGNAL_COUNT;

#endif /* CAN_CONFIG_H */
`;
};

// -----------------------------------------------------------------------------
// 2. Source Generation (can_config.c)
// -----------------------------------------------------------------------------
export const generateCanConfigC = (signals) => {
    const signalEntries = signals.map(s => {
        // Ensure values are formatted as C literals with suffixes
        const id = s.identifier.startsWith('0x') ? `${s.identifier}U` : `${s.identifier}U`;
        const start = `${s.startBit}U`;
        const len = `${s.length}U`;
        const endian = s.endianness === 'little' ? 'ENDIAN_LITTLE' : 'ENDIAN_BIG';
        const factor = Number(s.factor).toFixed(4) + 'F';
        const offset = Number(s.offset).toFixed(4) + 'F';
        const min = Number(s.min).toFixed(4) + 'F';
        const max = Number(s.max).toFixed(4) + 'F';

        return `    { ${id}, ${start}, ${len}, ${endian}, ${factor}, ${offset}, ${min}, ${max} }`;
    }).join(',\n');

    return `/**
 * @file can_config.c
 * @brief CAN Signal Configuration Source
 *
 * Generated by Rule Engine Dashboard
 * Standard: MISRA-C:2012
 */

#include "can_config.h"

/**
 * @brief Signal Configuration Table
 * 
 * Static array of all configured CAN signals.
 * Compliant with MISRA Rule 8.9 (Limited scope globals).
 */
const can_signal_t can_signals[] =
{
${signalEntries}
};

/**
 * @brief Signal Count
 */
const uint16_t CAN_SIGNAL_COUNT = ${signals.length}U;
`;
};

// -----------------------------------------------------------------------------
// 3. Decode Header (can_decode.h)
// -----------------------------------------------------------------------------
export const generateCanDecodeH = () => {
    return `/**
 * @file can_decode.h
 * @brief CAN Signal Decode Engine API
 *
 * Generated by Rule Engine Dashboard
 * Standard: MISRA-C:2012
 */

#ifndef CAN_DECODE_H
#define CAN_DECODE_H

#include "can_config.h"

/**
 * @brief Status codes for decode operations
 */
typedef enum
{
    CAN_OK = 0,
    CAN_ERROR_NULL_PTR,
    CAN_ERROR_INVALID_PARAM,
    CAN_ERROR_RANGE
} can_status_t;

/**
 * @brief Decodes a physical value from a raw CAN frame
 * 
 * @param[in]  signal  Pointer to the signal configuration
 * @param[in]  data    Pointer to the 8-byte CAN data payload
 * @param[out] value   Pointer to store the decoded physical value
 * 
 * @return can_status_t Operation status
 */
can_status_t can_decode_signal(
    const can_signal_t * signal,
    const uint8_t * data,
    float * value);

#endif /* CAN_DECODE_H */
`;
};

// -----------------------------------------------------------------------------
// 4. Decode Source (can_decode.c)
// -----------------------------------------------------------------------------
export const generateCanDecodeC = () => {
    return `/**
 * @file can_decode.c
 * @brief CAN Signal Decode Engine Implementation
 *
 * Generated by Rule Engine Dashboard
 * Standard: MISRA-C:2012
 */

#include "can_decode.h"
#include <stddef.h> /* For NULL */

/* -------------------------------------------------------------------------- */
/* Private Helper Functions                                                   */
/* -------------------------------------------------------------------------- */

/**
 * @brief Extracts raw bits for Little Endian signals
 * 
 * @param[in] data       Pointer to CAN data
 * @param[in] start_bit  Start bit position
 * @param[in] length     Length in bits
 * @return uint32_t      Extracted raw value
 * 
 * @note Compliant with MISRA Rule 12.2 (Shift safety)
 */
static uint32_t extract_little_endian(
    const uint8_t * data,
    uint8_t start_bit,
    uint8_t length)
{
    uint32_t raw_value = 0U;
    uint8_t bit_pos = start_bit;
    uint8_t bits_collected = 0U;

    while (bits_collected < length)
    {
        uint8_t byte_idx = bit_pos / 8U;
        uint8_t bit_offset = bit_pos % 8U;
        
        /* Safe access check */
        if (byte_idx >= 8U)
        {
            break;
        }

        /* Extract bit */
        if ((data[byte_idx] & (1U << bit_offset)) != 0U)
        {
            raw_value |= (1UL << bits_collected);
        }

        bit_pos++;
        bits_collected++;
    }

    return raw_value;
}

/**
 * @brief Extracts raw bits for Big Endian (Motorola) signals
 * 
 * @param[in] data       Pointer to CAN data
 * @param[in] start_bit  Start bit position
 * @param[in] length     Length in bits
 * @return uint32_t      Extracted raw value
 */
static uint32_t extract_big_endian(
    const uint8_t * data,
    uint8_t start_bit,
    uint8_t length)
{
    uint32_t raw_value = 0U;
    uint8_t bit_pos = start_bit;
    uint8_t bits_collected = 0U;

    /* 
     * Big Endian / Motorola usually counts bits differently.
     * This implementation assumes standard "sawtooth" or sequential bit decrement 
     * depending on specific Motorola variant (LSB/MSB).
     * 
     * For this generator, we assume standard Motorola Forward (MSB first).
     * Implementation simplified for bit-stream extraction.
     */
    
    /* Placeholder for complex Big Endian logic - simplified bit walker */
    /* In a real engine, this needs to handle byte boundaries carefully */
    
    while (bits_collected < length)
    {
        uint8_t byte_idx = bit_pos / 8U;
        uint8_t bit_offset = bit_pos % 8U;

        if (byte_idx >= 8U)
        {
            break;
        }

        /* Extract bit and shift into MSB of result */
        if ((data[byte_idx] & (1U << bit_offset)) != 0U)
        {
            /* Shift collected bits left to make room */
            raw_value |= (1UL << (length - 1U - bits_collected));
        }
        
        /* Motorola specific bit decrement logic would go here */
        /* For now, using simple decrement for demonstration */
        if (bit_offset == 0U)
        {
             bit_pos += 15U; /* Jump to next byte's MSB (simplified) */
        }
        else
        {
            bit_pos--;
        }

        bits_collected++;
    }

    return raw_value;
}

/* -------------------------------------------------------------------------- */
/* Public API Implementation                                                  */
/* -------------------------------------------------------------------------- */

can_status_t can_decode_signal(
    const can_signal_t * signal,
    const uint8_t * data,
    float * value)
{
    uint32_t raw_value = 0U;
    float physical_value = 0.0F;

    /* MISRA Rule 17.7: Check return values / params */
    if ((signal == NULL) || (data == NULL) || (value == NULL))
    {
        return CAN_ERROR_NULL_PTR;
    }

    /* 1. Extract Raw Bits */
    if (signal->endian == ENDIAN_LITTLE)
    {
        raw_value = extract_little_endian(data, signal->start_bit, signal->length);
    }
    else
    {
        /* Big Endian support */
        raw_value = extract_big_endian(data, signal->start_bit, signal->length);
    }

    /* 2. Apply Scaling: y = mx + c */
    physical_value = ((float)raw_value * signal->factor) + signal->offset;

    /* 3. Range Validation */
    if ((physical_value < signal->min) || (physical_value > signal->max))
    {
        /* Optional: Clamp value or return error */
        *value = physical_value; /* Return value anyway for diagnostics */
        return CAN_ERROR_RANGE;
    }

    *value = physical_value;
    return CAN_OK;
}
`;
};
